#!/usr/bin/env bash

set -euo pipefail

setxkbmap solemak

feh --bg-fill "$HOME/pictures/arch.jpg"

# Auto-repeat speed/delay
xset r rate 250 50

# Load ~/.Xresources so Urxvt doesn't look ugly
xrdb "$HOME/.Xresources"

# Run the Urxvt daemon to hopefully reduce latency and memory usage
urxvtd &!

# Make terminals transparent
xcompmgr &!

# Used by Solaar rules to allow switching browser tabs with mouse etc.
xbindkeys &!

# Start screenshot tool daemon
flameshot &!

# Start screensaver daemon
xscreensaver -no-splash &!

# Needed for notification daemon: https://wiki.archlinux.org/title/Dunst#Dunst_fails_to_start_via_systemd
systemctl --user import-environment DISPLAY

xss-lock -- xscreensaver-command -lock &!

# Otherwise X11 will crash on boot
xmonad --recompile

exec xmonad
