# Start Sway automatically on TTY login
if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    # Allow finding sway logs with journalctl --user --identifier sway
    exec systemd-cat --identifier=sway sway
fi
